services:
  nuget.next:
    image: hejiale010426/nuget-next
    build:
      context: .
      dockerfile: src/NuGet.Next/Dockerfile
    container_name: nuget-next
    ports:
      - "5000:8080"
    volumes:
      - ./nuget:/app/data # 请注意手动创建data目录，负责在Linux下可能出现权限问题导致无法写入
    environment:
      - Database:Type=SqLite
      - Database:ConnectionString=Data Source=/app/data/nuget.db
      - Mirror:Enabled=true
      - Mirror:PackageSource=https://api.nuget.org/v3/index.json
      - RunMigrationsAtStartup=true # 是否在启动时运行迁移，如果是第一次启动请设置为true
