name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 登录Docker Hub
      run: docker login -u aidotnet -p ${{ secrets.DOCKER }} 
    - name: 构建镜像
      run: docker build . --file src/NuGet.Next/Dockerfile --tag aidotnet/nuget-next 
    - name: 推送镜像
      run:  docker push aidotnet/nuget-next
